---
abstract: 'XSLT Interface to the Win32 Msxml2.DOMDocument library '
author:
  - 'Klaus Eichner <klaus03@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Win32-MinXSLT
requires:
  Carp: '0'
  Win32::OLE: '0'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/klaus03/Win32-MinXSLT
  repository: https://github.com/klaus03/Win32-MinXSLT.git
version: '0.04'
